---
- hosts: all
  become: yes

  roles:
    - kewlfft.aur
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.anaconda

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/extra-packages.yml
    # - include_tasks: tasks/conda.yml
    - include_tasks: tasks/q.yml
    
    - name: check if connection still works
      ping: