---
- hosts: all
  become: yes

  roles:
    - andrewrothstein.anaconda
    - role: andrewrothstein.conda-env
      conda_env_name: python3
      conda_env_environment: python3.yml

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/extra-packages.yml
    # - include_tasks: tasks/conda.yml
    - include_tasks: tasks/q.yml
    
    - name: check if connection still works
      ping: