---
- hosts: all
  # connection: local
  roles:
    - kewlfft.aur
    - role: uchida.miniconda
      become: yes
      miniconda_python: 3
      miniconda_prefix: /opt/miniconda
      miniconda_env:
        name: vagrant
        channels:
          - conda-forge
          - anaconda
        dependencies:
          - python=3.8
          - numpy
          - scipy
          - matplotlib
          - scikit-learn
          - pandas
          - jupyter

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/extra-packages.yml
