---
  - name: Replace Siglevel
    become: yes
    replace:
      path: /etc/pacman.conf
      regexp: "Required DatabaseOptional"
      replace: "Never"

  - name: Multilib
    become: yes
    blockinfile:
      path: /etc/pacman.conf
      marker: "# {mark} MULTILIB [ANSIBLE MANAGED BLOCK]"
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist
  
  - name: Install general packages
    become: yes
    package:
      force: yes
      update_cache: yes
      state: present
      name: "{{ item }}"
    with_items:
      - vim