---
  - name: Replace Siglevel
    become: yes
    replace:
      path: /etc/pacman.conf
      regexp: "Required DatabaseOptional"
      replace: "Never"

  - name: Multilib
    become: yes
    blockinfile:
      path: /etc/pacman.conf
      marker: "# {mark} MULTILIB [ANSIBLE MANAGED BLOCK]"
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist
  
  ## Q ##
  - name: Install general packages
    become: yes
    package:
      force: yes
      update_cache: yes
      state: present
      name: "{{ item }}"
    with_items:
      - vim
  
  ## Q ##
  - name: Install q dependancies
    become: yes
    package:
      force: yes
      update_cache: yes
      state: present
      name: "{{ item }}"
    with_items:
      - rlwrap
      - unzip
      - lib32-ncurses
      - lib32-zlib

  - name: Check q exists 
    command: ls /opt
    register: opt_dir
    changed_when: false
  
  - name: Download q
    get_url:
      url: https://kx.com/347_d0szre-fr8917_llrsT4Yle-5839sdX/3.6/linuxx86.zip
      dest: /tmp
    when: "opt_dir.stdout.find('q') == -1"
    
  - name: Extract q
    become: yes
    unarchive:
      src: /tmp/linuxx86.zip
      dest: /opt
      remote_src: yes
    when: "opt_dir.stdout.find('q') == -1"

  - name: Add q alias in bashrc
    blockinfile:
      path: /home/vagrant/.bashrc
      marker: "# {mark} Q [ANSIBLE MANAGED BLOCK]"
      block: |
        export QHOME=/opt/q
        export PATH=${PATH}:${QHOME}/l32/
        alias q="rlwrap ${QHOME}/l32/q"

  ## Miniconda ##

  - name: Check miniconda exists 
    command: ls /opt
    register: opt_dir
    changed_when: false

  - name: Download minicodna
    get_url:
      url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dest: /tmp
      checksum: sha256:879457af6a0bf5b34b48c12de31d4df0ee2f06a8e68768e5758c3293b2daf688
    when: "opt_dir.stdout.find('miniconda') == -1"

  - name: Install minicodna
    become: yes
    shell: bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda
    args:
      creates: /opt/miniconda
    when: "opt_dir.stdout.find('miniconda') == -1"

  - name: Add minicinda to path
    blockinfile:
      path: /home/vagrant/.bashrc
      marker: "# {mark} MINICONDA [ANSIBLE MANAGED BLOCK]"
      block: |
        export CONDA_HOME=/opt/miniconda
        export PATH=${PATH}:${CONDA_HOME}/bin/

  - name: Initialize minicodna
    shell: source /opt/miniconda/bin/activate; conda init


  ## Miniconda Packages ##
  # - name: Initialize minicodna
  #   shell: source /opt/miniconda/bin/activate; 
  # conda install -c anaconda scikit-learn numpy pandas jupyter -y -q
  # conda install -c conda-forge matplotlib -y -q