---
  ## Miniconda ##

  - name: Check miniconda exists 
    command: ls /opt
    register: opt_dir
    changed_when: false

  - name: Download minicodna
    get_url:
      url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dest: /tmp
      checksum: sha256:879457af6a0bf5b34b48c12de31d4df0ee2f06a8e68768e5758c3293b2daf688
    when: "opt_dir.stdout.find('miniconda') == -1"

  - name: Install minicodna
    become: yes
    shell: bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda
    args:
      creates: /opt/miniconda
    when: "opt_dir.stdout.find('miniconda') == -1"

  - name: Initialize minicodna
    shell: source /opt/miniconda/bin/activate; conda init; 

  - name: Add miniconda to path
    blockinfile:
      path: /home/vagrant/.bashrc
      marker: "# {mark} MINICONDA [ANSIBLE MANAGED BLOCK]"
      block: |
        export CONDA_HOME=/opt/miniconda
        export PATH=${PATH}:${CONDA_HOME}/bin/
        conda activate vagrant
    when: "opt_dir.stdout.find('miniconda') == -1"

  # Miniconda Packages ##
  - name: Install miniconda packages
    shell: |
      source /opt/miniconda/bin/activate;
      conda config --add channels anaconda;
      conda config --add channels conda-forge;
      conda create --name vagrant --file /tmp/requirements.txt -y

  - name: Generate jupyter server config
    shell: jupyter notebook --generate-config
    args:
      creates: /home/vagrant/.jupyter/jupyter_notebook_config.py

  - name: Setup jupyter server config
    replace:
      path: /home/vagrant/.jupyter/jupyter_notebook_config.py
      regexp: "# c.NotebookApp.allow_origin = ''"
      replace: "c.NotebookApp.allow_origin = '*'"
  
  - name: Setup jupyter server config
    replace:
      path: /home/vagrant/.jupyter/jupyter_notebook_config.py
      regexp: "# c.NotebookApp.ip = 'localhost'"
      replace: "c.NotebookApp.ip = '192.168.60.100'"
