---
  - name: Replace Siglevel
    become: yes
    replace:
      path: /etc/pacman.conf
      regexp: "Required DatabaseOptional"
      replace: "Never"
    when: ansible_facts['distribution'] == "ArchLinux"

  - name: Multilib
    become: yes
    blockinfile:
      path: /etc/pacman.conf
      marker: "# {mark} MULTILIB [ANSIBLE MANAGED BLOCK]"
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist
    when: ansible_facts['distribution'] == "ArchLinux"

  - name: Install general packages
    become: yes
    package:
      state: present
      name: "{{ item }}"
    with_items:
      - vim
      - perl
      - gcc
      - kernel-devel
      - kernel-headers
      - make
      - bzip2

  - name: Install q dependancies - CentOS
    become: yes
    package:
      state: present
      name: "{{ item }}"
    with_items:
      - net-tools
    when: ansible_facts['distribution'] == "CentOS"